default: &default
  docker:
    - image: circleci/node:8.9.1
checkout: &checkout
  - checkout
save: &save
  - save_cache:
      key: checkout-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/tmp
restore: &restore
  - restore_cache:
      keys:
        - checkout-{{ .Branch }}-{{ .Revision }}
install_and_build: &install_and_build
  - restore_cache:
      keys:
        - npm-cache-{{ checksum "package.json" }}
  - run:
      name: Install
      command: npm i
  - save_cache:
      key: npm-cache-{{ checksum "package.json" }}
      paths:
        - node_modules
  - run:
      name: Build
      command: npm run build
  - save_cache:
      key: npm-cache-{{ checksum "package.json" }}
      paths:
        - node_modules
test: &test
  - run:
      name: Test
      command: npm run test.record
  - run:
      name: Report
      command: npm run nyc report --reporter=text-lcov > coverage.lcov && codecov -t $CODECOV_TOKEN
version: 2
jobs:
  checkout:
    <<: *default
    working_directory: ~/tmp
    steps:
      [*checkout, *save]
  build:
    <<: *default
    working_directory: ~/tmp
    steps:
      [*restore, *install_and_build, *save]
  test:
    <<: *default
    working_directory: ~/tmp
    steps:
      [*restore, *test]
workflows:
  version: 2
  build-all:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build